# Generated by Django 5.0.1 on 2024-02-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_todo_user_todo_user_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user_object',
            new_name='user_objects',
        ),
    ]
